### ISSUE TITLE
I have a question about the static build of openssl

### ISSUE THREAD

**Issue by kdschlosser** [kiyolee/openssl1_1-win-build#4]
when I build openssl uusing the openssl-static project it does not create a openssl.lib file. the application one does create that lib. I would think the static build would create all of the lib files..

another thing. all of the projects need to have the target files names changed. it creates filenames like this `libcrypto-1_1.lib` where the -1_1 should not be there.

The other thing is when compiling using the static project I get a directory full of dll files.

**Comment by kiyolee** [comment]
openssl.lib is not something you will need. That was produced from a feature of openssl called applink/uplink (not exactly sure how they call it) to export entry points from exe file (didn't even know you can do that until producing this project). They use dllexport and that lead to automatically creating lib file for the exe file. The entry points are for bridging vc runtimes in case libssl-1_1.dll/libcrypto-1_1.dll are using different ones from the executable (openssl.exe in this case and may be you own).
The entry points are meant to be used dynamically. openssl.lib is not of much use and I can't find a way to avoid producing it. That's why openssl-static.exe does not produce one when it is not using dlls and there is no need of applink/uplink.
My solution produces both dll and static lib at the same time. For one reason, even if you only need dlls, some tests are specifically requiring the static libs to work. That's why I need to build both sets for auto testing. Even the official build scripts do that too.
The suffix -1_1 are there to follow the official build. Some previous releases even had x64 in there for 64-bit binaries. Thanks whoever removed that.

**Comment by kdschlosser** [comment]
OK I would have to check into what curl uses when it compiles.I do not know offhand if it specifically uses the static library from the executable.

**Comment by kiyolee** [comment]
To use static libraries of openssl, you need linking to: libcrypto-1_1-static.lib, libssl-1_1-static.lib and libz-static.lib. You may refer to openssl-static.props, that is used to build openssl-static.exe, for reference.
